language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  keep-history: true
  target-branch: gh-pages
  github-token: $github_token  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
